In [200]:
# n giriş resim boyutu
# f filtre boyutu

#padding(p) =piksel ekleme,dış çerçeveye 
#stride(s) = kaydırma adımı,ne kadar küçük ise o kadar iyi
# Eğer çıkış matrisi ile giriş matrisini eşit tutmak istiyorsanız padding artarsa stride da artmalı
# pooling(p) = ortaklama denir. böylece filtre boyutu azaltılır. (bazen havuzlama denir)    
# pooling deki filtre f dir. p ve s parametreleri kullanılarak giriş matrisinin boyutu azalır
def conv(stride=1,
        padding=True,
         padding_method={"dış çerçeveden ekle(opsiyonel)","sıfır ekle"},
        ): pass
    # ( (n+2p-f)/s) + 1) x ( (n+2p-f)/s) + 1)
    # p = (f-1)/2 ye göre seç ki girdi matrisi ile çıkanın boyu aynı olsun


In [201]:
import numpy as np

In [202]:
a = np.array([[1,2,4],[1,2,4]])
a

array([[1, 2, 4],
       [1, 2, 4]])

In [203]:
b = np.array([[1,1],[1,1]])
b

array([[1, 1],
       [1, 1]])

In [204]:
def conv_valid(input_matrix,
               kernel):
    
    '''
    [[1,2],   *(conv)  [[1,1],
     [1,2]]             [1,1]]       =  6
    '''
    
    row,column= kernel.shape
    
    result=0
    
    for i in range(row):
        
        for j in range(column):
            
            result+=kernel[i,j]*input_matrix[i,j]
            
    return(result)
            

In [205]:
conv_valid(a[0:2,1:3],b)

12

In [206]:
def padding(matrix:np.array,
            
            method="none",
            
            p = 0 ):
    
    
    row,column= matrix.shape
    
    
    if method=="none":
        
        padding_matrix = matrix
        
    
    elif method=="zero":
               
        zero_matrix = np.full((row+2*p, column+2*p), 0)
        
        zero_matrix[ p : -p ,  p : -p ] = matrix 
        
        padding_matrix = zero_matrix
        
        
    elif method=="from the frame":
        
                
        zero_matrix =np.full((row+2*p, column+2*p), 0)
        
        zero_matrix[p:-p,p:-p] = matrix
        
        
        for i in range(p):
    
                zero_matrix[i ,p:p+column] = matrix[p-i-1,:] #upside
    
                zero_matrix[i-p ,p:p+column] = matrix[-i-1,:] #underside
    
                zero_matrix[p:p+row,i] = matrix[:,p-i-1] #left side
    
                zero_matrix[p:p+row,-(i+1)] = matrix[:,-(p-i)] #right side
        
        
        zero_matrix[0:p,0:p]=zero_matrix[0:p,p].reshape(-1,1) #upper left corner

        zero_matrix[0:p,-p:]=zero_matrix[0:p,-(p+1)].reshape(-1,1) #upper right corner

        zero_matrix[-p:,0:p]=zero_matrix[-p:,p].reshape(-1,1) #lower left corner

        zero_matrix[-p:,-p:]=zero_matrix[-p:,-(p+1)].reshape(-1,1) #lower right corner
        
        padding_matrix = zero_matrix
        
    
    return(padding_matrix)
    
    

In [207]:
a = np.array([[1,20,-3],[1,2,3]])
padding(a,method="zero",p=2)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1, 20, -3,  0,  0],
       [ 0,  0,  1,  2,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [208]:
a = np.array([[1,20,-3],[1,2,3]])
padding(a,method="from the frame",p=2)

array([[ 1,  1,  1,  2,  3,  3,  3],
       [ 1,  1,  1, 20, -3, -3, -3],
       [20,  1,  1, 20, -3, -3, 20],
       [ 2,  1,  1,  2,  3,  3,  2],
       [ 1,  1,  1,  2,  3,  3,  3],
       [ 1,  1,  1, 20, -3, -3, -3]])

In [209]:
def pooling(matrix,method="mean"):
    
    row ,column = matrix.shape
    
    matrix_reshape = np.reshape(matrix,row*column)
    
    if method=="max":
        
        result=np.max(matrix_reshape)
        
    elif method=="min":
        
        result=np.min(matrix_reshape)
        
    elif method=="median":
        
        result=np.median(matrix_reshape)
        
    elif method=="mean":
        
        result=np.mean(matrix_reshape)
        
    
    return(result)
    

In [210]:
pooling(a)

4.0

In [211]:
pooling(a,method="max")

20

In [212]:
pooling(a,method="mean")

4.0

In [213]:
pooling(a,method="min")

-3

In [215]:
def conv(input_matrix,
         kernel,
        stride=1,
        padding_method="none",
        padding_number=1):pass
    
    
    
        
        